<?php
use Illuminate\Database\Seeder;
use App\Models\Order;

class OrdersTableSeeder extends Seeder
{

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '3',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '8',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '9',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '10',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '11',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '12',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '13',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '12',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '11',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '10',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '1',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '9',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '8',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '1',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '3',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '1',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '3',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '13',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '11',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '10',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '9',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '2',
            'user_id' => '8',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '3',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '2',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'created',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'cancelled',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'accepted',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '6',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'waiting',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '7',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'validated',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '5',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'finished',
            'customer_comment' => '',
            'feedback' => '',
        ]);
        Order::create([
            'category_id' => '1',
            'product_id' => '1',
            'parking_id' => '1',
            'user_id' => '4',
            'quantity' => '1',
            'unit_price' => '3.90',
            'total_price' => '3.90',
            'delay' => 'J+1',
            'status' => 'billed',
            'customer_comment' => '',
            'feedback' => '',
        ]);
    }
}

